services:
  promptmanager-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    image: promptmanager-web-dev
    env_file: .env
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=promptmanager-db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: bun run dev
    restart: "no"
